### ISSUE TITLE
The error occurs when a section layer is included in the target file.

### ISSUE THREAD

**Issue by sailtask** [simonoliver/UnityFigmaBridge#10]
**Describe the bug**

If Figma data contains a section layer, it cannot be imported into Unity properly.

**Version**

 - Unity Version: 2022.2.1f1
 - Platform: MacOS 13.2.1
 - Rendering Pipeline: URP 14.0.4

**Expected behavior**

- I want it to import correctly even if it contains section layers.
- I want section layers to be ignored in Unity.
- I would like to use the section layer itself for the purpose of organizing elements on Figma.

**Comment by simonoliver** [comment]
@sailtask  This should now be fixed in the latest version (1.0.4)- could you give it a try?
