### ISSUE TITLE
[BUG]EasingType elements seem to be missing

### ISSUE THREAD

**Issue by SatoruUeda** [simonoliver/UnityFigmaBridge#11]
**Describe the bug**
Error occurs during Document conversion when QUICK is used for Easing in Figma's Prototype Flow.

I added a QUICK definition and the conversion was successful.
But I am not sure if this is enough.
https://github.com/simonoliver/UnityFigmaBridge/blob/main/UnityFigmaBridge/Editor/FigmaApi/FigmaApiData.cs#L550

![image](https://user-images.githubusercontent.com/1707888/226801110-16c548ea-bbd7-4bfe-8d7a-592930e69941.png)

**Version**
Unity Version: 2022.2.1f1
Platform: MacOS 12.6
Rendering Pipeline: URP 14.0.4

**Comment by simonoliver** [comment]
@SatoruUeda Thanks for the report - yep your suggestion works great. I've also added some more missing Easing types to the API in the latest commit.
