### ISSUE TITLE
If two components using variants with the same name property and value, they are merged into one prefab.

### ISSUE THREAD

**Issue by sailtask** [simonoliver/UnityFigmaBridge#14]
**Describe the bug**
For example, if two different components on Figma (ButtonA and ButtonB) have the same name property name and value name "Type=State, Value=Enable" using the variant feature, they will be merged into "Type=State,Value=Enable.prefab", the data will be merged into the data and one of the buttons will not be displayed correctly.

**Expected behavior**
I would like each component to be imported as a unique prefab, even if the property and value names are the same.
Or, I would like Unity to tell me in the error message that it is due to duplicate property and value names.

**Additional context**
For now, this is handled by setting a unique value name for each component (e.g., "Name=ButtonA" & "Name=ButtonB")

**Comment by simonoliver** [comment]
@sailtask Thanks for reporting this - I've updated the package to add the name of the component set to the name of the prefab, so it should now be "ButtonA-Type=State,Valie=Enable.prefab" - they should not merge anymore
