### ISSUE TITLE
visual tree style demo

### ISSUE THREAD

**Issue by comoc** [simonoliver/UnityFigmaBridge#18]
Hi,

Thank you very much for publishing this wonderful project!

I would like a demo of a visual tree style UI.
Visual https://docs.unity3d.com/Manual/UIE-VisualTree.html
![](https://docs.unity3d.com/uploads/Main/VisualTreeExample.png)!

It would be very helpful if you could also show us how to add or remove elements.

Best regards,

**Comment by simonoliver** [comment]
@comoc - Hi, I could you add some more detail in what you are looking for?

The link you shared is for Unity's UI Elements system - this package at the moment supports Unity UI (the older system). Are you looking for UI Elements support? Or more how you would make something like that in Figma?

Regarding removing/adding elements, do you mean how you disable/enable them in code on the Unity side? 

Thanks,
Simon

**Comment by comoc** [comment]
Hi @simonoliver , thank you for your reply.

Here is what I meant..
> how you would make something like that in Figma?
It means a list view in which each list element is composed of various parts.

Hope I have explained it well.

Thanks,

**Comment by simonoliver** [comment]
@comoc - Sure, here's a quick demo - https://www.figma.com/file/eFbCtEV9MdoK7q98Lh8vAj/Tree-Layout-Demo?type=design&node-id=0%3A1&t=C0TRqXD9rpBkZyqI-1

**Comment by comoc** [comment]
Hi @simonoliver , Thank you very much for your response.
I was able to display your demo in Unity.
So the part about checkboxes and slider movement needs to be implemented in a C# script. I will try it.
