### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by StephenHodgson** [simonoliver/UnityFigmaBridge#2]
@simonoliver thanks so much for developing this!

Could you please tag your releases? I would very much appreciate it so I better track package updates 🙏

**Comment by StephenHodgson** [comment]
Also once you add your git tags people will be able to install via [OpenUPM](https://openupm.com/packages/com.simonoliver.unityfigma)

**Comment by simonoliver** [comment]
Ah yep, good catch - have added. And thanks for adding to OpenUPM!
