### ISSUE TITLE
Nothing imported from Figma[BUG]

### ISSUE THREAD

**Issue by VyperAD8XR** [simonoliver/UnityFigmaBridge#20]
I have unity 2021.3.16f. It appears that everything is importing when selecting Sync Document.  However, it just adds a blank canvas and EventSystem.

![image](https://user-images.githubusercontent.com/110571773/236351983-a6aff4b9-2824-4774-8ff4-0137f286dd5c.png)

**Comment by simonoliver** [comment]
Hey @VyperAD8XR - thanks for reporting this. It might be you haven't set a starting point for the prototype (you can see how to do this here) - https://help.figma.com/hc/en-us/articles/360040314193-Guide-to-prototyping-in-Figma . I'll add a warning for this in the future. You can check in the "figma/pages" folder to see if the page has been created. Can you let me know if this is the case and I'll close if so.

**Comment by simonoliver** [comment]
No worries, let us know if there's anything we can do to make it easier to learn how to use
