### ISSUE TITLE
Overlay frame transitions do not maintain relative scale

### ISSUE THREAD

**Issue by kamunimaximus** [simonoliver/UnityFigmaBridge#4]
Regardless of the size of the overlay they take up the entire screen

**Comment by simonoliver** [comment]
@kamunimaximus Could you elaborate on this? Right now there is a simple example transition (fade to black) that is driven by animation. If you could share an example Figma document link or screenshots that would help

**Comment by kamunimaximus** [comment]
![image](https://user-images.githubusercontent.com/5563544/222920532-547c5560-27d8-46a1-bf4f-539e9c36c38f.png)
when the frames are not the same size, an overlay is relative not scaled when testing the figma flow. In unity it scales 
![image](https://user-images.githubusercontent.com/5563544/222920550-fc307e14-e767-40dc-9fc4-6c9587f4a5de.png)

**Comment by simonoliver** [comment]
@kamunimaximus Curious about your use case here - right now I've assumed that all screens would be the same size (as you are designing for the same device). It looks like you want to have a modal popup appear on one of your screens. For this I'd recommend having this as a component that is placed on an existing screen, and simply made made visible in code. Let me know if you want an example for this.

**Comment by simonoliver** [comment]
@kamunimaximus I'm going to close this but feel free to reopen if you have any additional feedback.

**Comment by kamunimaximus** [comment]
> @kamunimaximus Curious about your use case here - right now I've assumed that all screens would be the same size (as you are designing for the same device). It looks like you want to have a modal popup appear on one of your screens. For this I'd recommend having this as a component that is placed on an existing screen, and simply made made visible in code. Let me know if you want an example for this.

Sorry for the late reply! The use case is for sure a modal, when setting a frame as overlay in figma you can specify overlay background and behaviour for the modal component. Right now the behaviour in figma and unity is vastly different
