### ISSUE TITLE
[BUG] while trying to sync document i come across the error "Error downloading Figma Server Render Image Data"

### ISSUE THREAD

**Issue by ElenakiOppa** [simonoliver/UnityFigmaBridge#40]
**Describe the bug**
Error downloading Figma Server Render Image Data
 System.Exception: Error downloading FIGMA Server Rendered Images: HTTP/1.1 400 Bad Request url 

![image_2024-04-12_012831017](https://github.com/simonoliver/UnityFigmaBridge/assets/57418997/d3f4b278-8aef-4bd9-ab36-43052620f01c)

**Comment by simonoliver** [comment]
Hey @ElenakiOppa  - you probably have run into an issue where Figma is trying to render images that are too large (I'll put in a catch for this in the future). For now can you try changing "Server Render Image Scale" in the settings to 1 and try again?

**Comment by ElenakiOppa** [comment]
Hello, thank you. that worked

**Comment by sharifulabedin** [comment]
hey @simonoliver i have changed the "Server Render Image Scale" to 1. but its still swing the message Error downloading Figma Server Render Image Data. how to solve?

**Comment by simonoliver** [comment]
It might be that one of the images that it's trying to render is too big (I think the max limit is 4k by 4k). You could see if you have any very large "vector" objects or those marker as export (or with "render" in the name)
