### ISSUE TITLE
[BUG] Error when entering DocumentURL in Setting because Figma URL is different

### ISSUE THREAD

**Issue by PAVDUP** [simonoliver/UnityFigmaBridge#44]
**Describe the bug**
The Figma URL path itself was the problem!!! Figma changed from a path starting with file/ to a path starting with design/, which caused the problem.
- original Figma path example : `https://www.figma.com/file/~~~`
- new Figma path example  : `https://www.figma.com/design/~~~`

**To Reproduce**
Currently, if you use the URL from Figma and enter it into the Document URL in the Setting, it will always fail.

**Expected behavior**
<Figma Document URL is not valid, please enter valid URL> window shown.

**Screenshots and example Figma File**
![image](https://github.com/simonoliver/UnityFigmaBridge/assets/98102252/bc418e8a-d533-49b7-a4cf-49bfddb993b6)

**Version**
 - Unity Version: [e.g. Unity 2022.3.21]
 - Platform [e.g. Windows 11]
 - Rendering Pipeline [e.g Built-in render pipepline or URP 12.1.10]

**Temparary Solution**

Just Changing `https://www.figma.com/design/ABCDEFGH~~` (current path) link to `https://www.figma.com/file/ABCDEFGH~~` (old path). This problem can be solved.

**Comment by PAVDUP** [comment]
> i have the same issue. perhaps we can change the code then?
> 
> maybe the code here can be updated:
> 
> public static async Task GetFigmaDocument public static (bool, string) GetFigmaDocumentIdFromUrl

I think we can. But I want to wait for owner's feedback and approve! And also I didn't check code, so I have to check and investigate code inside!

**Comment by simonoliver** [comment]
Hey - sorry for the delay. I'm spending less time on Unity work at the moment. I've just pushed a fix for this, let me know if you have any issues.

**Comment by shacharoz** [comment]
@simonoliver totaly understandable!
it is just that your plugin is very promising, but I couldn't make it work.
i will try again tomorrow and inform here.

**Comment by PAVDUP** [comment]
> @simonoliver totaly understandable! it is just that your plugin is very promising, but I couldn't make it work. i will try again tomorrow and inform here.

The creator seems to have fixed the issue, please try installing the latest version via UPM again.

@simonoliver Since using this plugin, I have been able to improve my understanding of the UGUI and the speed of UI adaptation. Thank you so much for your hard work and for creating such a great tool.

**Comment by shacharoz** [comment]
@simonoliver i confirm problem is fixed.
i would be happy to improve a bit the Readme instructions to make them a bit more clear on the early setup.
well done overall.
